* Android

** Emulator
http://developer.android.com/guide/developing/devices/emulator.html

Check the port number on the title
> telnet localhost [port]

*** commands
- Change network speed to EDGE
network speed edge
- Change network speed to full
network speed full
- Set battery capacity
power capacity [value]
- Disconnect battery charger
power status not-charging
- Send SMS
sms send [number] "[text]"

*** Communicate two emulators
- Make one emulator call the other: dial the port number

** Dalvik Debug Monitor Service: DDMS
*** File explorer
*** Logcat
*** Traceview
*** Hierarchyview
** Components
*** Activity
User interface
*** Service
Long running, UI-less processes
Interaction with remote processes
*** Broadcast Subscriber
Receives and reacts upon external or internal events.
Subscriber in publish/subscribe pattern.
Events are represented by the Intent class.
BroadcastReceiver receives and responds to broadcast events.
*** Content providers
Store and share data across applications
Uses database-style interface
Handles interprocess communication
** Building
http://developer.android.com/guide/developing/building
*** Define resources
http://developer.android.com/guide/topics/resources
Strings: strings, string arrays, plurals.
Typically stored in res/values-[country code]/*.xml
Accessed by other resources as @string/string_name
Accessed in Java as
R.string.string_name
*** Implement application classes
*** Package application
*** Install and run application

** User Interface layout

Defined in XML files: res/layout/*.xml
Accessed in Java as: R.layout.layout_name
Accessed by other resources as: @layout/layout_name
The application can change the layout depending on the screen size or even the orientation: res/layout-land/main.xml

*** R.java
Generated at compile time.
