#+TITLE: Acta de la reunión con la dirección de Ventura24
#+AUTHOR: Comité de Empresa UGT
#+LANGUAGE: es
#+LATEX_HEADER: \usepackage[spanish]{babel}

** Acta

Acta de la reunión ordinaria de Ventura24, convocada y realizada el 6 de octubre de 2014, a las 11:00 de la mañana, en las oficinas de Ventura24 en Madrid, calle Leganitos, 47.

** Asistentes

- Zuriñe Sáenz de Viteri
- Jose María Calzada
- María Pérez Ferro
- José San Leandro
- Felipe Crespo
- José Alberto Torres
- Miguel Ángel Sánchez
- Tamara Martínez

Contando con la aprobación de los directivos presentes, José San Leandro ofició de presidente de comité, y Tamara Martínez, como secretaria, registró esta acta.

** Temas tratados

- Presentación del acta de constitución del comité.

- Presentación del delegado de prevención de riesgos.

- Presentación de una agenda completa para el inicio de las reuniones.

- Conciliación de la periodicidad de las reuniones ordinarias.

- Temperatura ambiental.

- Comunicación abierta.

- Entrega de las propuestas “Transparencia” y “Appraisals”.

** Anuncios

- El 10 de Octubre se harán públicas las medidas del grupo para el Have your say, tal como se anunció.

- Verificación de la temperatura de cada planta.

- Las reuniones generales darán más importancia a la información local del negocio de Ventura24 y de Once.

** Agenda para la próxima reunión

No quedó definida una agenda para la siguiente reunión, pero sí un compromiso por parte del comité de facilitar, con una mayor antelación, la agenda de temas a tratar.

Tampoco se decidió la fecha exacta de la próxima reunión, pero quedó acordada la periodicidad de futuras reuniones ordinarias de forma trimestral.

La empresa se ofreció a escuchar y discutir cuestiones que surjan sin necesidad de tener que esperar a la reunión trimestral.

** Resumen de la reunión

La reunión en general transcurrió de forma calmada y con espíritu co\-la\-bo\-ra\-dor.

Tras la presentación de los roles adquiridos por los miembros del comité, se expusieron los principales puntos de disconformidad o preocupación de los empleados de Ventura24, reflejados en su mayoría en el pasado “Have Your Say”, y la posterior recogida de quejas e inquietudes anónimas (“La Urna”).

Uno de los primeros puntos discutidos giró en torno a la temperatura ambiental. A este respecto se acordó, en extensión de lo expuesto en la última reunión general de resultados de la urna, una verificación de los valores por parte del delegado de prevención de riesgos (Felipe Crespo), junto con Jose María Calzada y el Office Manager (Franziska Keil). La empresa expuso argumentos a favor de establecer una forma de actuación coordinada que tenga en cuenta las características de cada planta en cuanto a la potencia de los equipos de aire acondicionado o bombas de calor, número de personas, y necesidad de reciclaje de aire.

En otro orden de cosas, la empresa sostiene que en Ventura24 se ha intentado siempre mantener lo más informado posible a todos los empleados. Se ha convenido que partir de ahora en las reuniones generales se tratarán temas de índole local de forma explícita.

La empresa ha manifestado que es del interés de todos conseguir una mayor participación por parte de los trabajadores en las reuniones ya sea con preguntas, sugerencias o aclaraciones, y siempre con responsabilidad y respeto. En este sentido la empresa ha trasmitido ciertas dudas sobre la conveniencia de volver a utilizar mecanismos de comunicación anónimos como la urna.

El comité de empresa, por su parte, preguntará en la siguiente reunión general sobre la opinión de la Empresa ante las propuestas de “Transparencia” y “Appraisals” presentadas en la reunión.

Se levantó la sesión a las 12:00 de la mañana.


Acta presentada por Tamara Martínez, y aprobada por todos los miembros del comité de empresa.
